version: "2.3"
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3,sqs
      - AWS_DEFAULT_REGION=us-west-2
      - EDGE_PORT=4566
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
  redis:
    image: redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
      - localstack
      - redis
    restart: always
    command: flask --debug run --port=5432 --host=0.0.0.0
    volumes:
      - ./app:/app
      - ./docs:/docs
      - ./logs:/logs
    ports:
      - "5432:5432"